apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: default
spec:
  selector:
    app: ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-depl
  namespace: default
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: gcr.io/kubernetes-346311/front-end-1:latest
          ports:
            - containerPort: 80
              name: ui
          # env:
          #   - name: API
          #     value: "http://api-service/"
          #   - name: AUTH_TOKEN
          #     value: "valid_token"
